export const customers = [
  { src: './cisco.webp', alt: 'CISCO', },
  { src: './att.webp', alt: 'AT&T', },
  { src: './ciena2.webp', alt: 'CIENA', },
  { src: './veritas.webp', alt: 'VERITAS', },
  { src: './nutanix.webp', alt: 'NUTANIX', },
  { src: './nvidia.webp', alt: 'NVIDIA', },
  { src: './telefonica.webp', alt: 'Telefonica', },
  { src: './bt.webp', alt: 'BT', },
  { src: './vodafone.webp', alt: 'VODAFONE', },
  { src: './bbva.webp', alt: 'BBVA', },
  { src: './santander.webp', alt: 'Santander', },
  { src: './sabadell.webp', alt: 'Sabadell', },
  { src: './caixa.webp', alt: 'Caixa', },
  { src: './abanca.webp', alt: 'Abanca', },
  { src: './cajamar.webp', alt: 'Cajamar', },
  { src: './kutxabank.webp', alt: 'Kutxabanc', },
  { src: './unicaja.webp', alt: 'Unicaja', },
  { src: './ing.webp', alt: 'ING', },
  { src: './euronet.webp', alt: 'Euronet', },
  { src: './lidl.webp', alt: 'LIDL', },
  { src: './alcampo.webp', alt: 'Alcampo', },
  { src: './eci.webp', alt: 'ECI', },
];