export const customers = [
  { src: '../public/cisco.webp', alt: 'CISCO', },
  { src: '../public/att.webp', alt: 'AT&T', },
  { src: '../public/ciena2.webp', alt: 'CIENA', },
  { src: '../public/veritas.webp', alt: 'VERITAS', },
  { src: '../public/nutanix.webp', alt: 'NUTANIX', },
  { src: '../public/nvidia.webp', alt: 'NVIDIA', },
  { src: '../public/telefonica.webp', alt: 'Telefonica', },
  { src: '../public/bt.webp', alt: 'BT', },
  { src: '../public/vodafone.webp', alt: 'VODAFONE', },
  { src: '../public/bbva.webp', alt: 'BBVA', },
  { src: '../public/santander.webp', alt: 'Santander', },
  { src: '../public/sabadell.webp', alt: 'Sabadell', },
  { src: '../public/caixa.webp', alt: 'Caixa', },
  { src: '../public/abanca.webp', alt: 'Abanca', },
  { src: '../public/cajamar.webp', alt: 'Cajamar', },
  { src: '../public/kutxabank.webp', alt: 'Kutxabanc', },
  { src: '../public/unicaja.webp', alt: 'Unicaja', },
  { src: '../public/ing.webp', alt: 'ING', },
  { src: '../public/euronet.webp', alt: 'Euronet', },
  { src: '../public/lidl.webp', alt: 'LIDL', },
  { src: '../public/alcampo.webp', alt: 'Alcampo', },
  { src: '../public/eci.webp', alt: 'ECI', },
];