export const projects = [
  {
    image: "./proyecto5.webp",
    title: 'Proyecto 5 Games Hub',
    titleEn: 'Project 5 Games Hub',
    text: "Creación de 3 juegos mediante VITE, componentizado, responsivo y haciendo únicamente uso de JavaScript para su creación y funcionalidad.", 
    textEn: "Creation of 3 games using VITE, componentized, responsive and I only used Javascript to the creation and functionality.",
    date: 'Mayo 2024',
    dateEn: 'May 2024',
    link: "https://github.com/DanielSalvatierraSanchez/Proyecto_5_Games_Hub_4All.git",
    url: "https://proyecto-5-games-hub-4-all.vercel.app/",
    target: "_blank",
  },
  {
    image: "./proyecto4.webp",
    title: 'Proyecto 4 Portfolio',
    titleEn: 'Project 4 Portfolio',
    text: "Creación de mi Portfolio mediante VITE, componentizado, escalable, responsivo, con eventos,...", 
    textEn: "Creation of my Portfolio using VITE, componentized, scalable, responsive, with events,...",
    date: 'Marzo 2024',
    dateEn: 'March 2024',
    link: "https://github.com/DanielSalvatierraSanchez/Portfolio.git",
    url: "https://portfolio-daniel-salvatierra.vercel.app/",
    target: "_blank",
  },
  {
    image: "./proyecto3.webp",
    title: 'Proyecto 3 Picturest',
    titleEn: 'Project 3 Picturest',
    text: "Réplica de Pinterest mediante VITE, toque personal, componentizado, haciendo llamadas a una API,...", 
    textEn: "Pinterest replication using VITE, componentized, making API calls,...",
    date: 'Febrero 2024',
    dateEn: 'February 2024',
    link: "https://github.com/DanielSalvatierraSanchez/Proyecto_3_Pinterest_FEB24.git",
    url: "https://proyecto-3-picturest-mar24.netlify.app/",
    target: "_blank",
  },
  {
    image: "./proyecto2.webp",
    title: "Proyecto 2 Gamestore",
    titleEn: "Project 2 Gamestore", 
    text: "Creación de una tienda de videojuegos mediante VITE, creando 2 filtros con funcionalidad conjunta,...", 
    textEn: "Creating a video game store using VITE, creating 2 filters with joint functionality,...",
    date: 'Enero 2024',
    dateEn: 'January 2024',
    link: "https://github.com/DanielSalvatierraSanchez/Proyecto_2_Gamestore_ENE24.git",
    url: "https://proyecto-2-gamestore-feb24.netlify.app/",
    target: "_blank",
  },
  {
    image: "./proyecto1.webp",
    title: "Proyecto 1 GameRoom",
    titleEn: "Project 1 GameRoom", 
    text: "Simulación de una tienda de videojuegos, un proyecto básico, buenas prácticas, responsivo,...", 
    textEn: "Simulation of a video game store, a basic project, best practice, responsive,...",
    date: 'Noviembre 2023',
    dateEn: 'November 2023',
    link: "https://github.com/DanielSalvatierraSanchez/Proyecto_1_Game_Room_NOV23.git",
    url: "https://proyecto-1-gameroom-nov23.netlify.app/",
    target: "_blank",
  },
];